name: public-pool-panel-85
services:
  app:
    image: nginx:alpine
    container_name: pool-panel-85
    hostname: pool-panel-85
    restart: unless-stopped
    ports:
      - "85:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - host.docker.internal:host-gateway
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: "Pool Panel — real-time pool stats and management"
  tagline:
    en_us: Просмотр пулов и статистики
  developer: public-pool-btc.ru
  author: public-pool-btc.ru
  icon: https://raw.githubusercontent.com/oliverw/miningcore/master/logo.png
  thumbnail: https://raw.githubusercontent.com/oliverw/miningcore/master/logo.png
  title:
    en_us: Pool Panel
  category: Miningcore Pool UI
  port_map: "85"
