name: public-pool-bitcoin-cash
services:
  app:
    cpu_shares: 90
    command:
    - /usr/bin/bitcoind
    - -printtoconsole
    - -server
    - -prune=550
    - -wallet=default
    - -zmqpubhashblock=tcp://127.0.0.1:7002
    - -rpcbind=0.0.0.0
    - -rpcport=9002
    - -rpcallowip=0.0.0.0/0
    - -port=8334
    - -rpcuser=pooluser
    - -rpcpassword=poolpassword
    container_name: Node-BCH
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    hostname: Node-BCH
    image: theretromike/nodes:bitcoincash
    labels:
      icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/bch.png
    ports:
    - mode: ingress
      target: 7002
      published: '7002'
      protocol: tcp
    - mode: ingress
      target: 9002
      published: '9002'
      protocol: tcp
    - mode: ingress
      target: 8334
      published: '8334'
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/bch
      target: /root/.bitcoin
      bind:
        create_host_path: true
    x-casaos:
      ports:
      - container: '7002'
        description:
          en_us: 'Container Port: 7002'
      - container: '9002'
        description:
          en_us: 'Container Port: 9002'
      - container: '8334'
        description:
          en_us: 'Container Port: 8334'
      volumes:
      - container: /root/.bitcoin
        description:
          en_us: 'Container Path: /root/.bitcoin'
    devices: []
    cap_add: []
    environment: []
    networks:
    - pool_network
    - default
    privileged: false
networks:
  default:
    name: public-pool-bitcoin-cash_default
  pool_network:
    external: true
x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  description:
    en_us: Bitcoin Cash Cryptocurrency Node. Can be used in conjunction with Miningcore
      Apps to solo mine.
  developer: public-pool-btc.ru
  hostname: ''
  icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/bch.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9002'
  scheme: http
  store_app_id: public-pool-bitcoin-cash
  tagline:
    en_us: Bitcoin Cash Cryptocurrency Node.
  thumbnail: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/bch.png
  title:
    custom: Bitcoin Cash (BCH) Node
    en_us: Bitcoin Cash (BCH) Node
