name: public_pool_miningcore_xmr
services:
  app:
    container_name: public_pool_miningcore_xmr
    image: theretromike/miningcore:legacy
    restart: always
    volumes:
      - /media/ZimaOS-HD/miningcore_xmr/coins.json:/app/build/coins.json
      - /media/ZimaOS-HD/miningcore_xmr/config.json:/app/config.json
      - /media/ZimaOS-HD/vtc:/.vertcoin
    ports:
      - "4001:4001"
      - "6101-6115:6101-6115"
      - "6501-6515:6501-6515"
      - "6601-6615:6601-6615"
      - "6701-6715:6701-6715"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Miningcore Mining Pool (Monero/XMR).
  tagline:
    en_us: Miningcore Pool XMR
  developer: public-pool-btc.ru
  author: public-pool-btc.ru
  icon: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/pool-ui/img/favicon.png
  thumbnail: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/pool-ui/img/favicon.png
  title:
    en_us: Miningcore XMR
  category: Miningcore Pool UI
  port_map: "8888"
