name: molepool-web-ui
services:
  app:
    container_name: Molepool-Web-UI
    build: .
    image: public-pool/molepool-web-ui:latest
    restart: unless-stopped
    ports:
      - "82:80"
    networks:
      - pool_network
networks:
  pool_network:
    external: true
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: public-pool-btc.ru
  category: Miningcore Pool UI
  description:
    en_us: Панель molepool.com. Pool | Algorithm | Miners | Hashrate | Network Diff | Price | Block Reward | Min Payout | Pool Fee 1.5%. Порт 82. pool_network + Miningcore.
  developer: public-pool-btc.ru
  icon: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/Apps/img/icon-molepool.png
  thumbnail: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/Apps/img/icon-molepool.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '82'
  scheme: http
  store_app_id: molepool-web-ui
  tagline:
    en_us: Molepool — порт 82 • Diff, Price, Reward, 1.5% fee
  title:
    custom: Web UI Molepool (порт 82)
    en_us: Web UI Molepool (порт 82)
