name: retro-mike-pepepow
services:
  app:
    cpu_shares: 90
    container_name: Node-PEPEW
    hostname: Node-PEPEW
    image: theretromike/nodes:pepew
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    restart: unless-stopped
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/pepew
      target: /root/.PEPEPOWcore
      bind:
        create_host_path: true
    ports:
    - target: 7014
      published: '7014'
      protocol: tcp
    - target: 9014
      published: '9014'
      protocol: tcp
    command:
    - /app/PEPEPOWd
    - -printtoconsole
    - -server
    - -wallet=default
    - -zmqpubhashblock=tcp://0.0.0.0:7014
    - -rpcbind=0.0.0.0
    - -rpcport=9014
    - -rpcallowip=0.0.0.0/0
    - -rpcuser=pooluser
    - -rpcpassword=poolpassword
    labels:
      icon: https://cryptologos.cc/logos/pepe-pepe-logo.png
    networks:
    - pool_network
    - default
    privileged: false
networks:
  default:
    name: retro-mike-pepepow_default
  pool_network:
    external: true
x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  developer: public-pool-btc.ru
  description:
    en_us: PepePOW (PEPEW) full node with RPC+ZMQ. Ports RPC 9014, ZMQ 7014.
  hostname: ''
  icon: https://cryptologos.cc/logos/pepe-pepe-logo.png
  thumbnail: https://cryptologos.cc/logos/pepe-pepe-logo.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9014'
  scheme: http
  store_app_id: retro-mike-pepepow
  tagline:
    en_us: PepePOW (PEPEW) Node
  title:
    custom: PepePOW (PEPEW) Node
    en_us: PepePOW (PEPEW) Node
