name: public-pool-zephyr
services:
  app:
    cpu_shares: 90
    container_name: Node-ZEPH
    hostname: Node-ZEPH
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    image: supertypo/zephyrd:latest
    ports:
      - target: 17766
        published: '17766'
        protocol: tcp
      - target: 17767
        published: '17767'
        protocol: tcp
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/nodes/zeph
        target: /app/.zephyr
        bind:
          create_host_path: true
    restart: unless-stopped
    networks:
      - pool_network
      - default

networks:
  default:
    name: public-pool-btc.ru_default
  pool_network:
    external: true

x-casaos:
  architectures:
    - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  description:
    en_us: Zephyr Protocol full node for Miningcore pool. RPC 17767. Data at /media/ZimaOS-HD/nodes/zeph
  developer: public-pool-btc.ru
  icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/zeph.png
  thumbnail: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/zeph.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '17767'
  scheme: http
  store_app_id: public-pool-node-zeph
  tagline:
    en_us: Zephyr (ZEPH) Node
  title:
    custom: Zephyr (ZEPH) Node
    en_us: Zephyr (ZEPH) Node
