name: solopool-web-ui
services:
  app:
    container_name: SoloPool-Web-UI
    build: .
    image: public-pool/solopool-web-ui:latest
    restart: unless-stopped
    ports:
      - "84:80"
    networks:
      - pool_network
networks:
  pool_network:
    external: true
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: public-pool-btc.ru
  category: Miningcore Pool UI
  description:
    en_us: Панель solopool.org. Pool Hashrate | Blocks | Luck | Network Diff | Price | Block Reward | Min Payout | Pool Fee 1.5%. Порт 84. pool_network + Miningcore.
  developer: public-pool-btc.ru
  icon: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/Apps/img/icon-solopool-org.png
  thumbnail: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/Apps/img/icon-solopool-org.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '84'
  scheme: http
  store_app_id: solopool-web-ui
  tagline:
    en_us: SoloPool.org — порт 84
  title:
    custom: Web UI SoloPool.org (порт 84)
    en_us: Web UI SoloPool.org (порт 84)
