name: public-pool-btc.ru
services:
  app:
    cpu_shares: 90
    container_name: Node-SPACE
    hostname: Node-SPACE
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    image: spaceworksco/spacecoin:latest
    ports:
      - target: 9133
        published: '9133'
        protocol: tcp
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/nodes/space
        target: /root/.komodo/SPACE
        bind:
          create_host_path: true
    restart: unless-stopped
    networks:
      - pool_network
      - default

networks:
  default:
    name: public-pool-btc.ru_default
  pool_network:
    external: true

x-casaos:
  architectures:
    - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  description:
    en_us: Spacecoin full node for Miningcore pool. RPC 9133. Data at /media/ZimaOS-HD/nodes/space
  developer: public-pool-btc.ru
  icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/space.png
  thumbnail: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/space.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9133'
  scheme: http
  store_app_id: public-pool-node-space
  tagline:
    en_us: Spacecoin (SPACE) Node
  title:
    custom: Spacecoin (SPACE) Node
    en_us: Spacecoin (SPACE) Node
