name: public-pool-spacecoin
services:
  app:
    cpu_shares: 90
    container_name: Node-SPACE
    hostname: Node-SPACE
    image: spaceworksco/spacecoin:latest
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    restart: unless-stopped
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/space
      target: /root/.komodo/SPACE
      bind:
        create_host_path: true
    ports:
    - target: 9133
      published: '9133'
      protocol: tcp
    labels:
      icon: https://cryptologos.cc/logos/spacecoin-space-logo.png
    networks:
    - pool_network
    - default
    privileged: false
networks:
  default:
    name: public-pool-spacecoin_default
  pool_network:
    external: true
x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  developer: public-pool-btc.ru
  description:
    en_us: Spacecoin (SPACE) full node for Miningcore pool. RPC 9133.
  hostname: ''
  icon: https://cryptologos.cc/logos/spacecoin-space-logo.png
  thumbnail: https://cryptologos.cc/logos/spacecoin-space-logo.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9133'
  scheme: http
  store_app_id: public-pool-node-space
  tagline:
    en_us: Spacecoin (SPACE) Node
  title:
    custom: Spacecoin (SPACE) Node
    en_us: Spacecoin (SPACE) Node
