name: public-pool-btc.ru
services:
  app:
    cpu_shares: 90
    container_name: Node-RVN
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    image: alpine:3.20
    command:
    - sh
    - -lc
    - echo 'Skeleton container for RVN. Replace image/command with real node daemon.'
      && sleep infinity
    ports:
    - target: 7010
      published: '7010'
      protocol: tcp
    - target: 9010
      published: '9010'
      protocol: tcp
    networks:
    - pool_network
    - default

networks:
  default:
    name: public-pool-btc.ru_default
  pool_network:
    external: true

x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  description:
    en_us: Skeleton node app for Ravencoin (RVN). Replace container image with real
      daemon.
  developer: public-pool-btc.ru
  icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/rvn.png
  thumbnail: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/rvn.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9010'
  scheme: http
  store_app_id: public-pool-node-rvn
  tagline:
    en_us: RVN Node (skeleton)
  title:
    custom: Ravencoin (RVN) Node
    en_us: Ravencoin (RVN) Node
