name: public-pool-bitcoin-sv
services:
  app:
    cpu_shares: 90
    image: theretromike/nodes:bitcoinsv
    container_name: Node-BSV
    hostname: Node-BSV
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/bsv
      target: /root/.bitcoin
      bind:
        create_host_path: true
    ports:
    - target: 8338
      published: '8338'
      protocol: tcp
    - target: 9005
      published: '9005'
      protocol: tcp
    - target: 7005
      published: '7005'
      protocol: tcp
    command:
    - bitcoind
    - -printtoconsole
    - -server
    - -prune=550
    - -txindex=0
    - -wallet=default
    - -excessiveblocksize=0
    - -maxstackmemoryusageconsensus=0
    - -minminingtxfee=0.00000001
    - -port=8338
    - -zmqpubhashblock=tcp://0.0.0.0:7005
    - -rpcbind=0.0.0.0
    - -rpcport=9005
    - -rpcallowip=0.0.0.0/0
    - -rpcuser=pooluser
    - -rpcpassword=poolpassword
    labels:
      icon: https://cryptologos.cc/logos/bitcoin-sv-bsv-logo.png
    networks:
    - pool_network
    - default

    privileged: false
networks:
  default:
    name: public-pool-bitcoin-sv_default
  pool_network:
    external: true

x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  developer: public-pool-btc.ru
  description:
    en_us: 'Bitcoin SV full node with RPC+ZMQ. Data: /media/ZimaOS-HD/nodes/bsv. Ports:
      P2P 8338, RPC 9005, ZMQ 7005.'
  hostname: ''
  icon: https://cryptologos.cc/logos/bitcoin-sv-bsv-logo.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9005'
  scheme: http
  store_app_id: public-pool-bitcoin-sv
  title:
    custom: Bitcoin SV (BSV) Node
    en_us: Bitcoin SV (BSV) Node
