name: public-pool-litecoin-cash
services:
  app:
    cpu_shares: 90
    container_name: Node-LCC
    hostname: Node-LCC
    build: .
    image: pool-node-lcc:latest
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    restart: unless-stopped
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/lcc
      target: /root/.litecoincash
      bind:
        create_host_path: true
    ports:
    - target: 9062
      published: '9062'
      protocol: tcp
    - target: 7062
      published: '7062'
      protocol: tcp
    - target: 62458
      published: '62458'
      protocol: tcp
    command:
    - litecoincashd
    - -printtoconsole
    - -server
    - -prune=550
    - -wallet=default
    - -zmqpubhashblock=tcp://0.0.0.0:7062
    - -rpcbind=0.0.0.0
    - -rpcport=9062
    - -rpcallowip=0.0.0.0/0
    - -rpcuser=pooluser
    - -rpcpassword=poolpassword
    labels:
      icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/lcc.png
    networks:
    - pool_network
    - default
    privileged: false
networks:
  default:
    name: public-pool-litecoin-cash_default
  pool_network:
    external: true
x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  developer: public-pool-btc.ru
  description:
    en_us: 'Litecoin Cash (LCC) full node with RPC+ZMQ. Pruned. Data: /media/ZimaOS-HD/nodes/lcc. Ports: P2P 62458, RPC 9062, ZMQ 7062.'
  hostname: ''
  icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/lcc.png
  thumbnail: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/lcc.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9062'
  scheme: http
  store_app_id: public-pool-node-lcc
  tagline:
    en_us: 'Litecoin Cash (LCC) Node'
  title:
    custom: 'Litecoin Cash (LCC) Node'
    en_us: 'Litecoin Cash (LCC) Node'
