name: web-ui-pool-secondary
services:
  app:
    container_name: Web-UI-Pool-Secondary
    image: theretromike/miningcorewebui:latest
    restart: always
    volumes:
      - /media/ZimaOS-HD/miningcore:/app/miningcore
    ports:
      - "85:8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - SERVER_IP=${SERVER_IP:-host.docker.internal}
      - API_BASE_URL=http://${SERVER_IP:-host.docker.internal}:4000/api
      - MININGCORE_HOST=${SERVER_IP:-host.docker.internal}
      - PLATFORM=ZIMAOS
      - POOL_NAME=public-pool-btc.ru
      - POSTGRES_DATABASE=miningcore
      - POSTGRES_HOST=${SERVER_IP:-host.docker.internal}
      - POSTGRES_PASSWORD=miningcore
      - POSTGRES_USER=miningcore
      - PUID=1000
      - STRATUM_HOST=public-pool-btc.ru
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: MiningCore Web UI с PoolConfiguration: Setup Database Schema, Refresh Master Coin List, Generate Pool Config File. Управление монетами. Порт 85.
  tagline:
    en_us: Pool Configuration — порт 85
  developer: public-pool-btc.ru
  author: public-pool-btc.ru
  icon: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/Apps/img/icon-pool-secondary.png
  thumbnail: https://raw.githubusercontent.com/Sert1985n/-CasaOS-ZimaOS-app-store-with-Miningcore-Pool-UI-/main/Apps/img/icon-pool-secondary.png
  store_app_id: public-pool-miningcore-webui-85
  title:
    en_us: Web UI — Вторичный пул — порт 85
  category: Miningcore Pool UI
  port_map: "85"
