name: miningcore-webui-85
services:
  app:
    container_name: Miningcore-Web-UI
    image: theretromike/miningcorewebui:latest
    restart: always
    volumes:
      - /media/ZimaOS-HD/miningcore:/app/miningcore
    ports:
      - "85:8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - pool_network
      - default
    environment:
      - SERVER_IP=${SERVER_IP:-miningcore}
      - API_BASE_URL=http://${SERVER_IP:-miningcore}:4000/api
      - MININGCORE_HOST=${SERVER_IP:-miningcore}
      - PLATFORM=ZIMAOS
      - POOL_NAME=public-pool-btc.ru
      - POSTGRES_DATABASE=miningcore
      - POSTGRES_HOST=${POSTGRES_HOST:-host.docker.internal}
      - POSTGRES_PASSWORD=miningcore
      - POSTGRES_USER=miningcore
      - PUID=1000
      - STRATUM_HOST=public-pool-btc.ru
networks:
  pool_network:
    external: true
  default:
    name: miningcore-webui-85_default
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: MiningCore Web UI с PoolConfiguration: Setup Database Schema, Refresh Master Coin List, Generate Pool Config File. Управление монетами. Порт 85.
  tagline:
    en_us: Pool Configuration — порт 85
  developer: public-pool-btc.ru
  author: public-pool-btc.ru
  icon: https://raw.githubusercontent.com/TheRetroMike/retromike-umbrel-app-store/master/retro-mike-miningcore-webui/webui.png
  thumbnail: https://raw.githubusercontent.com/TheRetroMike/retromike-umbrel-app-store/master/retro-mike-miningcore-webui/webui.png
  store_app_id: miningcore-webui-85
  title:
    en_us: Miningcore Web UI (порт 85)
  category: Miningcore Pool UI
  port_map: "85"
