name: public-pool-nexa
services:
  app:
    cpu_shares: 90
    container_name: Node-NEXA
    image: bchunlimited/nexad-rostrum
    deploy:
      resources:
        limits:
          memory: 8192M
          cpus: '1'
    ports:
    - target: 9077
      published: '9077'
      protocol: tcp
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/nexa
      target: /data
      bind:
        create_host_path: true
    restart: unless-stopped
    networks:
    - pool_network
    - default

networks:
  default:
    name: public-pool-nexa_default
  pool_network:
    external: true

x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  description:
    en_us: 'Nexa node/rostrum container (image: bchunlimited/nexad-rostrum). Configure
      as needed; data at /data.'
  developer: public-pool-btc.ru
  hostname: Node-NEXA
  icon: https://cryptologos.cc/logos/nexa-nexa-logo.png
  thumbnail: https://cryptologos.cc/logos/nexa-nexa-logo.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9077'
  scheme: http
  store_app_id: public-pool-nexa
  tagline:
    en_us: Nexa (NEXA) Node
  title:
    custom: Nexa (NEXA) Node
    en_us: Nexa (NEXA) Node
