name: public-pool-frencoin
services:
  app:
    cpu_shares: 90
    container_name: Node-FREN
    hostname: Node-FREN
    image: theretromike/nodes:frencoin
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    restart: unless-stopped
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/fren
      target: /root/.frencoin
      bind:
        create_host_path: true
    ports:
    - target: 9045
      published: '9045'
      protocol: tcp
    - target: 7045
      published: '7045'
      protocol: tcp
    - target: 8791
      published: '8791'
      protocol: tcp
    command:
    - frencoind
    - -printtoconsole
    - -server
    - -prune=550
    - -wallet=default
    - -zmqpubhashblock=tcp://0.0.0.0:7045
    - -rpcbind=0.0.0.0
    - -rpcport=9045
    - -rpcallowip=0.0.0.0/0
    - -rpcuser=pooluser
    - -rpcpassword=poolpassword
    labels:
      icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/fren.png
    networks:
    - pool_network
    - default
    privileged: false
networks:
  default:
    name: public-pool-frencoin_default
  pool_network:
    external: true
x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  developer: public-pool-btc.ru
  description:
    en_us: 'Frencoin (FREN) full node with RPC+ZMQ. Pruned. Data: /media/ZimaOS-HD/nodes/fren. Ports: P2P 8791, RPC 9045, ZMQ 7045.'
  hostname: ''
  icon: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/fren.png
  thumbnail: https://cdn.jsdelivr.net/npm/cryptocurrency-icons@0.18.1/128/color/fren.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9045'
  scheme: http
  store_app_id: public-pool-node-fren
  tagline:
    en_us: 'Frencoin (FREN) Node'
  title:
    custom: 'Frencoin (FREN) Node'
    en_us: 'Frencoin (FREN) Node'
