name: public-pool-vertcoin
services:
  app:
    cpu_shares: 90
    container_name: Node-VTC
    hostname: Node-VTC
    image: lukechilds/vertcoind:latest
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: '2'
    restart: unless-stopped
    volumes:
    - type: bind
      source: /media/ZimaOS-HD/nodes/vtc
      target: /data
      bind:
        create_host_path: true
    ports:
    - target: 7008
      published: '7008'
      protocol: tcp
    - target: 9008
      published: '9008'
      protocol: tcp
    - target: 5889
      published: '5889'
      protocol: tcp
    command:
    - -printtoconsole
    - -server
    - -prune=550
    - -wallet=default
    - -zmqpubhashblock=tcp://0.0.0.0:7008
    - -rpcbind=0.0.0.0
    - -rpcport=9008
    - -rpcallowip=0.0.0.0/0
    - -port=5889
    - -rpcuser=pooluser
    - -rpcpassword=poolpassword
    labels:
      icon: https://cryptologos.cc/logos/vertcoin-vtc-logo.png
    networks:
    - pool_network
    - default
    privileged: false
networks:
  default:
    name: public-pool-vertcoin_default
  pool_network:
    external: true
x-casaos:
  architectures:
  - amd64
  author: public-pool-btc.ru
  category: Cryptocurrency Nodes
  developer: public-pool-btc.ru
  description:
    en_us: Vertcoin (VTC) full node with RPC+ZMQ. Pruned. Ports P2P 5889, RPC 9008, ZMQ 7008.
  hostname: ''
  icon: https://cryptologos.cc/logos/vertcoin-vtc-logo.png
  thumbnail: https://cryptologos.cc/logos/vertcoin-vtc-logo.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: '9008'
  scheme: http
  store_app_id: public-pool-vertcoin
  tagline:
    en_us: Vertcoin (VTC) Node
  title:
    custom: Vertcoin (VTC) Node
    en_us: Vertcoin (VTC) Node
